apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "employee-api.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "employee-api.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
