apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "employee-api.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
