apiVersion: v1
kind: Secret
metadata:
  name: {{ include "employee-api.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "employee-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
