replicaCount: 1

image:
  tag: "latest"

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  hosts:
    - host: employee-api.dev.local
      paths:
        - path: /
          pathType: Prefix

namespace: employee-api-dev

env:
  DB_HOST: "employee-db-postgresql"
  DB_PORT: "5432"
  DB_NAME: "employeedb_dev"
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "dev"
